var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
function decorateMap(){if(void 0!=localStorage.getItem(userInfo.account+"baseNoise")&&void 0!=localStorage.getItem(userInfo.account+"perlinNoise")){JSON.parse(localStorage.getItem(userInfo.account+"baseNoise"));var a=JSON.parse(localStorage.getItem(userInfo.account+"perlinNoise"))}else{var b=GenerateWhiteNoise(75,75,userInfo.account);a=GeneratePerlinNoise(b,6,.6);localStorage.setItem(userInfo.account+"baseNoise",JSON.stringify(b));localStorage.setItem(userInfo.account+"perlinNoise",JSON.stringify(a))}for(b=
0;b<a.length;b++)for(var c=0;c<a[b].length;c++){var d=DistanceSquared(c,b,75,75)/68;a[b][c]>=d*d&&(.6<=a[b][c]&&.7>=a[b][c]?(ctxbackdecor.globalAlpha=.3,ctxbackdecor.drawImage(tempImages["tile4.webp"],c*tileSize,b*tileSize,tileSize,tileSize)):.35<=a[b][c]&&.45>=a[b][c]?(ctxbackdecor.globalAlpha=.3,ctxbackdecor.drawImage(tempImages["tile9.webp"],c*tileSize,b*tileSize,tileSize,tileSize)):(ctxbackdecor.globalAlpha=.3,ctxbackdecor.drawImage(tempImages["tile6.webp"],c*tileSize,b*tileSize,tileSize,tileSize)))}}
function DistanceSquared(a,b,c,d){a=Math.abs(a-.5*c);b=Math.abs(b-.5*d);return Math.sqrt(a*a+b*b)}function GenerateWhiteNoise(a,b,c){null!=c&&Math.seedrandom(c);noise=GetEmptyArray(a,b);for(c=0;c<b;c++)for(var d=0;d<a;d++)noise[c][d]=Math.round(Math.random());return noise}function GetEmptyArray(a,b){var c=[];for(y=0;y<b;y++){var d=[];for(x=0;x<a;x++)d.push(0);c.push(d)}return c}function Interpolate(a,b,c){return a*(1-c)+c*b}
function GeneratePerlinNoise(a,b,c){var d=a[0].length,r=a.length,t=GetEmptyArray(d,r),u=1,g=0;for(--b;0<=b;b--){var h=parseInt(Math.pow(2,b),10),q=1/h;u*=c;g+=u;for(var e=0;e<r;e++)for(var f=parseInt(parseInt(e/h,10)*h,10),k=parseInt(f+h,10)%r,m=(e-f)*q,l=0;l<d;l++){var n=parseInt(parseInt(l/h,10)*h,10),p=parseInt(n+h,10)%d,v=(l-n)*q;n=Interpolate(a[f][n],a[k][n],m);p=Interpolate(a[f][p],a[k][p],m);t[e][l]+=parseFloat(Interpolate(n,p,v)*u)}}for(e=0;e<r;e++)for(l=0;l<d;l++)t[e][l]/=g;return t}
function getMousePos(a){var b=document.getElementById("gamemap"),c=document.getElementById("gamewrapper");if(""!=c.style.transform){var d=a.clientX/ratio-(parseFloat(b.style.transform.split(",")[0].split("(")[1])+parseFloat(parseFloat(c.style.transform.split(",")[0].split("(")[1])/ratio));a=a.clientY/ratio-(parseFloat(b.style.transform.split(",")[1])+parseFloat(c.style.transform.split(",")[1])/ratio)}else d=a.clientX/ratio-parseFloat(b.style.transform.split(",")[0].split("(")[1]),a=a.clientY/ratio-
parseFloat(b.style.transform.split(",")[1]);isNaN(a)&&(a=0);return{x:d,y:a-43}}function isInside(a,b){return a.x>b.x&&a.x<b.x+b.width&&a.y<b.y+b.heigth&&a.y>b.y}
function clickOnMap(a){if(draggingMap||!depositCoord.updated)return!1;var b=getMousePos(a);if(roadBuilder){if(-1==activeObjId)return!1;document.getElementsByClassName("savemapeditor")[0].classList.contains("disablebtn")&&document.getElementsByClassName("savemapeditor")[0].classList.remove("disablebtn");a=b.x/tileSize-.16;var c=(b.y+38)/tileSize-1;a-=a%1;c-=c%1;var d=a*tileSize,r=c*tileSize;if(existTileCell(d,r))return document.getElementsByClassName("croadsav")[0].innerText=parseInt(userInfo.maxroads-
cellsArray.length),redrawMapCells(),!1;if(0>=parseInt(userInfo.maxroads-cellsArray.length))return makeNotif(2,"Maximum objects on the map reached"),!1;var t={width:10,height:5,x:parseInt(d+tileSize/2-5),y:parseInt(r+tileSize+10)},u=!1;Object.entries(objectsArray).some(function(g){g=g[1];if(!g.collide)return!1;objectmap=void 0!=buildings[g.objid]?100==g.objid?{width:g.width-20,height:g.height-20,x:g.posx+8,y:g.posy+15}:{width:g.width-20,height:g.height-30,x:g.posx+8,y:g.posy+25}:{width:g.width,height:g.height,
x:g.posx,y:g.posy-25};if(isCollide(t,objectmap))return u=!0,setTimeout(function(){makeNotif(2,"Object is colliding with something, try putting it somewhere else");var h=Math.floor(99999*Math.random());elemGM=document.getElementById("gamemap");elemGM.insertAdjacentHTML("beforeend","<div id='2conid"+h+"' style='top:"+objectmap.y+"px;width:"+objectmap.width+"px;height:"+objectmap.height+"px;left:"+objectmap.x+"px' class='testpoint'></div>");setTimeout(function(){document.getElementById("2conid"+h).remove()},
1E3)},0),!0});if(u)return!1;d=activeObjId;a=new cells(a,c,tilePreloadMap[d].w,tilePreloadMap[d].h,tilePreloadMap[d].image,d);a.draw();cellsArray.push(a);document.getElementsByClassName("croadsav")[0].innerText=parseInt(userInfo.maxroads-cellsArray.length);redrawMapCells();return!1}Object.entries(buttonsArray).some(function(g){var h=g[1];if(""!=g[1].extrainfo){if(isInside(b,{x:h.posx,y:h.posy,width:h.width,heigth:h.height}))return g=h.extrainfo,clickSound.play(),openHouseSettings(g),!0}else{var q=
h.identif;if(isInside(b,{x:h.posx,y:h.posy,width:h.width,heigth:h.height}))return clickSound.play(),Object.entries(objectsArray).some(function(e){if(e[1].identif==q){var f=e[1];e=f.image;var k=document.createElement("div");k.style.width=e.width+"px";k.style.height=e.height+"px";k.style.background="url("+e.currentSrc+")";document.getElementsByClassName("containercontenttop")[0].innerHTML="<div style='background:url(/styles/img/"+tileNames[f.objid].img+");width: "+e.width+"px; height: "+e.height+"px;'></div>";
var m=f.width;e=f.height;k=parseInt(f.posx);k=parseInt(k+m/2);m=parseInt(f.posy);m=parseInt(m+e/2);var l=parseInt(distance(depositCoord.posx+buildings[100].w/2,depositCoord.posy+buildings[100].h/2,k,m)/userInfo.timeforcut);0>=l&&(l=1);k=6E4*l;e=Math.floor(k%864E5/36E5);k=Math.floor(k%36E5/6E4);m="";0<e&&(m=m+""+e+"h");0<k&&(m=""!=m?m+" "+k+"m":k+"m");e="Wait time is "+m;void 0!=tileNames[f.objid].woodmin&&0<tileNames[f.objid].woodmin&&(e=e+'<div class="mgtop10">Reward:</div>'+tileNames[f.objid].woodmin+
" - "+tileNames[f.objid].woodmax+" of Wood <span class='woodiconmin'></span>");void 0!=tileNames[f.objid].foodmin&&0<tileNames[f.objid].foodmin&&(e=0>=tileNames[f.objid].woodmin?e+'<div class="mgtop10">Reward:</div>':e+"</br>",e=e+tileNames[f.objid].foodmin+" - "+tileNames[f.objid].foodmax+" of Food <span class='foodiconmin'></span>");document.getElementsByClassName("containercontentmedium")[0].innerHTML="<center>"+getTextObject(parseInt(f.objid)).split(";")[1]+"</br>"+e+"</center>";getPriceObj(parseInt(f.objid))>
userInfo.gold?document.getElementsByClassName("containercontentbottom")[0].innerHTML="<div class='smallbtn actioncuts disablebtn'><div class='innersmall'>"+getTextObject(parseInt(f.objid)).split(";")[0]+"</div></div>":(document.getElementsByClassName("containercontentbottom")[0].innerHTML="<div class='smallbtn actioncuts'><div class='innersmall'>"+getTextObject(parseInt(f.objid)).split(";")[0]+"</div></div>",document.getElementsByClassName("actioncuts")[0].addEventListener("click",function(){loadingScreen(!0);
postData(apiLink+"/cutnow/"+q,"POST",{}).then(function(n){if(1==n.result){cachedPaths={};isVisible(document.getElementsByClassName("draghead")[0])&&hide(document.getElementsByClassName("draghead")[0]);var p=document.createElement("div");p.style.left=f.posx-f.width/2-7+"px";p.style.top=f.posy+(f.height-30)+"px";p.style.position="absolute";p.style.zIndex=2;document.getElementById("gamemap").append(p);appendProgressBar(p,f.objid+";"+q.replace("-",";"),n.waittime);calculateTime(n.waittime,"pr"+f.objid+
";"+q.replace("-",";"),60*l);updateUserStats(n,!1);redrawCutButtons(q,!1)}else postResultFalse(n);loadingScreen(!1)})}));isVisible(document.getElementsByClassName("draghead")[0])||show(document.getElementsByClassName("draghead")[0]);return!0}}),!0}})}var clickSpawnVillager=-1;
function savemap(){for(var a="",b=$jscomp.makeIterator(cellsArray),c=b.next();!c.done;c=b.next())c=c.value,""!=a&&(a+=";"),a+=c.posx/tileSize+","+c.posy/tileSize+","+c.tileid;loadingScreen(!0);postData(apiLink+"/roadbuild","POST",{finalmap:a}).then(function(d){1==d.result?makeNotif(0,d.msg):postResultFalse(d);loadingScreen(!1)})}function deletecutButtons(){contextbtns.clearRect(0,0,5100,5100)}
function redrawCutButtons(a,b){b&&prepareMatrixPath();contextbtns.clearRect(0,0,5100,5100);if(null!=a){for(var c=$jscomp.makeIterator(buttonsArray),d=c.next();!d.done;d=c.next())if(d=d.value,d.identif==a){d=buttonsArray.indexOf(d);-1!==d&&buttonsArray.splice(d,1);break}c=$jscomp.makeIterator(buttonsArray);for(d=c.next();!d.done;d=c.next())if(d=d.value,null!=a&&d.identif==a){d=buttonsArray.indexOf(d);-1!==d&&buttonsArray.splice(d,1);break}}c=$jscomp.makeIterator(buttonsArray);for(d=c.next();!d.done;d=
c.next())d.value.draw()}var timeoutMouse;
document.getElementById("gamemap").addEventListener("mousemove",function(a){clearTimeout(timeoutMouse);timeoutMouse=setTimeout(function(){if(!depositCoord.updated||roadBuilder||draggingMap)return!1;var b=getMousePos(a);Object.entries(buttonsArray).some(function(c){c=c[1];if(isInside(b,{x:c.posx,y:c.posy,width:c.width,heigth:c.height}))return document.getElementById("gamemap").style.cursor="pointer",!0;document.getElementById("gamemap").style.cursor="grab"})},6)});