var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(b){return b.raw=b};$jscomp.createTemplateTagFirstArgWithRaw=function(b,a){b.raw=a;return b};$jscomp.arrayIteratorImpl=function(b){var a=0;return function(){return a<b.length?{done:!1,value:b[a++]}:{done:!0}}};$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};$jscomp.makeIterator=function(b){var a="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return a?a.call(b):$jscomp.arrayIterator(b)};
$jscomp.arrayFromIterator=function(b){for(var a,c=[];!(a=b.next()).done;)c.push(a.value);return c};$jscomp.arrayFromIterable=function(b){return b instanceof Array?b:$jscomp.arrayFromIterator($jscomp.makeIterator(b))};var cellsArray=[],cellsBackup=[],tileSize=68,lastActiveObj=null,activeObjId=-1,intervalChat,buclChat=0,connectedChat=!1,socketChat,reconnectChat=!0,startHeightChat=30,showtimer=!0,chatPing,totalMessages=[],cachedPaths={},easystar=new EasyStar.js;easystar.setAcceptableTiles([0,2]);
easystar.setTileCost([0],2);easystar.setTileCost([2],1);easystar.disableDiagonals();
function mapReadyLoaded(){var b="";objectsPanelEditor.forEach(function(e){b+='<div data-objid="'+e+'" style="background:url(/styles/img/'+tilePreloadMap[e].img+')" class="card mapdecoritem"></div>'});document.getElementById("objcontents").innerHTML=b;for(var a=document.getElementsByClassName("mapdecoritem"),c=function(){null!=lastActiveObj&&lastActiveObj.classList.contains("activedecor")&&lastActiveObj.classList.remove("activedecor");var e=this.dataset.objid;this.classList.contains("activedecor")||
(this.classList.add("activedecor"),lastActiveObj=this);activeObjId=e},d=0;d<a.length;d++)a[d].addEventListener("click",c,!1);document.getElementsByClassName("roadbutton")[0].addEventListener("click",function(){if(this.classList.contains("disablebtn"))return!1;clickSound.play();if(0>=performanceMode)return makeNotif(2,"The map editor is not available in performance mode"),!1;if(!depositCoord.updated&&void 0==houses[100])return makeNotif(2,"You need to build a WareHouse first"),!1;if(roadBuilder)return!1;
loadingScreen(!0);null!=lastActiveObj&&lastActiveObj.classList.contains("activedecor")&&lastActiveObj.classList.remove("activedecor");activeObjId=-1;cellsBackup=[].concat($jscomp.arrayFromIterable(cellsArray));roadBuilder=!0;forceCloseContainerHouse(!1);dragdivs.forEach(function(e){isVisible(document.getElementsByClassName("drag"+e)[0])&&hide(document.getElementsByClassName("drag"+e)[0])});document.body.insertAdjacentHTML("beforeend","<div class='roadqcontent'><span class='avroads'>Available Objects: <span class='croadsav'>"+
(userInfo.maxroads-cellsArray.length)+'</span></span><img class=\'imgroadq\' src=\'/styles/img/roadquant.webp\'/></div><div class="containermapeditor"><div class="smallbtn savemapeditor disablebtn"><div class="innersmall">Save</div></div><div class="smallbtn satfilter1 closeroadeditor"><div class="innersmall">Close</div></div></div>');2<=performanceMode?TweenLite.to(".bottombar",{onComplete:function(){TweenLite.to(".containermapeditor",{duration:.5,bottom:"-6"})},duration:.5,right:"-310"}):(document.getElementsByClassName("bottombar")[0].style.right=
"-310px",document.getElementsByClassName("containermapeditor")[0].style.bottom="-6px");editorisopen||(deletecutButtons(),drawGrid(5100,5100));isVisible(document.getElementById("mapobjects"))||show(document.getElementById("mapobjects"));document.getElementsByClassName("closeroadeditor")[0].addEventListener("click",function g(f){f.stopImmediatePropagation();f.stopPropagation();f.preventDefault();clickSound.play();roadBuilder=!1;cellsArray=[].concat($jscomp.arrayFromIterable(cellsBackup));context.clearRect(0,
0,5100,5100);depositCoord.updated&&redrawCutButtons(null,!1);stopMapEditor();2<=performanceMode?TweenLite.to(".containermapeditor",{onComplete:function(){document.getElementsByClassName("containermapeditor")[0].remove();TweenLite.to(".bottombar",{duration:.5,right:"0px"})},duration:.5,bottom:"-66px"}):(document.getElementsByClassName("bottombar")[0].style.right="0px",document.getElementsByClassName("containermapeditor")[0].remove());document.getElementsByClassName("roadqcontent")[0].remove();isVisible(document.getElementById("mapobjects"))&&
hide(document.getElementById("mapobjects"));activeObjId=-1;restartVillagerJobs();this.removeEventListener("click",g)});document.getElementsByClassName("savemapeditor")[0].addEventListener("click",function k(g){g.stopImmediatePropagation();g.stopPropagation();g.preventDefault();if(this.classList.contains("disablebtn"))return!1;cachedPaths={};clickSound.play();roadBuilder=!1;context.clearRect(0,0,5100,5100);depositCoord.updated&&redrawCutButtons(null,!0);stopMapEditor();2<=performanceMode?TweenLite.to(".containermapeditor",
{onComplete:function(){document.getElementsByClassName("containermapeditor")[0].remove();TweenLite.to(".bottombar",{duration:.5,right:"0px"})},duration:.5,bottom:"-66px"}):(document.getElementsByClassName("bottombar")[0].style.right="0px",document.getElementsByClassName("containermapeditor")[0].remove());document.getElementsByClassName("roadqcontent")[0].remove();savemap();isVisible(document.getElementById("mapobjects"))&&hide(document.getElementById("mapobjects"));activeObjId=-1;restartVillagerJobs();
this.removeEventListener("click",k)});loadingScreen(!1)})}function restartVillagerJobs(){Object.keys(villagerJobs).forEach(function(b){"stop"==villagerJobs[b].status&&giveVillagerJob(b)})}function drawCellsHousePut(){editorisopen||(editorisopen=!0,drawGrid(5100,5100),deletecutButtons())}function stopCellsEditor(b,a){editorisopen&&0>=parseInt(b)&&(editorisopen=!1,a&&(context.clearRect(0,0,5100,5100),depositCoord.updated&&redrawCutButtons(null,!0)))}
function drawGrid(b,a){context.clearRect(0,0,b,a);context.lineWidth=1;context.strokeStyle="#ffffff66";context.beginPath();for(x=0;x<=b;x+=tileSize)context.moveTo(x,0),context.lineTo(x,a);for(y=22;y<=a;y+=tileSize)context.moveTo(0,y),context.lineTo(b,y);context.stroke();context.closePath()}var cells=function(b,a,c,d,e,f){this.width=c;this.height=d;this.image=e;this.posx=b*tileSize;this.posy=a*tileSize;this.tileid=f};
cells.prototype.draw=function(){null!=this.image&&context2.drawImage(this.image,this.posx,this.posy,this.width,this.height)};function stopMapEditor(){context2.clearRect(0,0,5100,5100);redrawMapCells()}
function existTileCell(b,a){for(var c=$jscomp.makeIterator(cellsArray),d=c.next();!d.done;d=c.next())if(d=d.value,void 0!=d&&d.posx==b&&d.posy==a)if(isFence(activeObjId)){if(isFence(d.tileid))return c=cellsArray.indexOf(d),-1!==c&&cellsArray.splice(c,1),!0}else if(!isFence(d.tileid))return c=cellsArray.indexOf(d),-1!==c&&cellsArray.splice(c,1),!0;return!1}
function findNearestRoad(b,a){for(var c=[-1,-1],d=Infinity,e=0;e<matrix.length;e++)for(var f=0;f<matrix[e].length;f++)if(0===matrix[e][f]){var g=Math.sqrt(Math.pow(e-b,2)+Math.pow(f-a,2));g<d&&(d=g,c=[e,f])}return c}
function spawnVillager(b,a){var c=Math.floor(99999*Math.random());elemmap=document.createElement("div");elemmap.style.left=Math.round(b)+"px";elemmap.style.top=Math.round(a)+"px";elemmap.dataset.villagerid=c;elemmap.classList="villager";document.getElementById("gamemap").append(elemmap);return c}var villagerPaths={},villagerIndex={},villagerTweenLine={},villagerStartDate={},matrix=[];
function prepareMatrixPath(){for(var b=0;75>b;b++)matrix[b]=Array(74).fill(0);Object.entries(housesStaticOnMap).forEach(function(a){var c=$jscomp.makeIterator(a);a=c.next().value;c=c.next().value;if(void 0==c.id)return!1;c=parseInt(c.id);var d=parseInt(a.split(";")[0]);a=parseInt(a.split(";")[1]);addBuildOnMatrix(c,d,a,!1)});Object.entries(mapobjects).forEach(function(a){var c=$jscomp.makeIterator(a);a=c.next().value;c=c.next().value;c=parseInt(c.id);var d=parseInt(a.split("-")[0]);a=parseInt(a.split("-")[1]);
changeItemsOnMatrix(c,d,a,1)});easystar.setGrid(matrix)}function changeItemsOnMatrix(b,a,c,d){a=Math.round(a/tileSize);c=Math.round(c/tileSize);if(null!=tileNames[b]){var e=Math.round(tileNames[b].w/tileSize),f=Math.round(tileNames[b].h/tileSize);15<=b&&17>=b&&(f+=1,--c);for(b=0;b<e;b++)for(var g=0;g<f;g++)matrix[c+g][a+b]=d}0==d&&easystar.setGrid(matrix)}
function addBuildOnMatrix(b,a,c,d){a=Math.floor(a/tileSize);c=Math.floor(c/tileSize)+1;if(null!=buildings[b]){c=100==b||101==b?c-1:c+1;var e=roundToEven(buildings[b].w,tileSize)/tileSize-1,f=roundToEven(buildings[b].h,tileSize)/tileSize-1;105==b&&(e+=1);100!=b&&101!=b&&(f-=2);for(b=0;b<e;b++)for(var g=0;g<f;g++)matrix[parseInt(c+g)][parseInt(a+b)]=1}d&&easystar.setGrid(matrix)}
function moveVillager(b,a,c,d){var e=document.querySelectorAll('[data-villagerid="'+c+'"]')[0];if(void 0==e)return!1;var f=e.style.left.slice(0,e.style.left.length-2),g=e.style.top.slice(0,e.style.top.length-2),k=Math.round(f/tileSize),l=Math.round(g/tileSize);void 0!=cachedPaths[k+","+l+","+b+","+a]?(villagerPaths[c]=cachedPaths[k+","+l+","+b+","+a],villagerIndex[c]=1,void 0!=villagerTweenLine[c]&&(villagerTweenLine[c].kill(),delete villagerTweenLine[c]),villagerStartDate[c]=Date.now(),followPath(c,
e)):(easystar.findPath(k,l,b,a,function(h){if(null!=h)0<h.length&&h.slice(),0<h.length&&(cachedPaths[k+","+l+","+b+","+a]=h,villagerPaths[c]=h,villagerIndex[c]=1,void 0!=villagerTweenLine[c]&&(villagerTweenLine[c].kill(),delete villagerTweenLine[c]),villagerStartDate[c]=Date.now(),followPath(c,e));else{if(d)return villagerJobs[c].status="stop",makeNotif(1,"An obstacle prevents a villager from moving"),!1;h=findNearestRoad(a,b);-1!=h&&moveVillager(h[1],h[0],c,!0)}}),easystar.calculate())}
function followPath(b,a){if(void 0==villagerPaths[b]||0>=villagerPaths[b].length)return!1;var c=villagerPaths[b][villagerIndex[b]];villagerIndex[b]+=1;villagerTweenLine[b]=TweenLite.to(a,.5,{onComplete:function(){void 0!=villagerPaths[b]&&villagerIndex[b]<villagerPaths[b].length?followPath(b,a):(villagerTweenLine[b].kill(),delete villagerTweenLine[b],clickSpawnVillager!=b&&(0<villagerJobs[b].jobs.length?doJobs(b):giveVillagerJob(b)))},ease:"none",left:c.x*tileSize+13,top:c.y*tileSize})}
function findLongestPath(b,a){for(var c=[],d=0;75>d;d++)c.push(Array(74).fill(0));d=$jscomp.makeIterator(cellsArray);for(var e=d.next();!e.done;e=d.next())e=e.value,void 0!=e&&(0>e.tileid||15<e.tileid||(c[e.posx/tileSize][e.posy/tileSize]=1));d=[];for(d.push({x:b,y:a,steps:0});0<d.length;){var f=d.shift();e=f.x;f=f.y;75>e+1&&1===c[e+1][f]&&(d.push({x:e+1,y:f}),c[e+1][f]=c[e][f]+1);20>f+1&&1===c[e][f+1]&&(d.push({x:e,y:f+1}),c[e][f+1]=c[e][f]+1);0<=e-1&&1===c[e-1][f]&&(d.push({x:e-1,y:f}),c[e-1][f]=
c[e][f]+1);0<=f-1&&1===c[e][f-1]&&(d.push({x:e,y:f-1}),c[e][f-1]=c[e][f]+1)}d=0;for(e=0;e<c.length;e++)for(f=0;f<c[e].length;f++)if(c[e][f]>d){d=c[e][f];var g={x:e,y:f}}return 0===d?{x:b,y:a}:g}function getRightx(b){for(var a=$jscomp.makeIterator(cellsArray),c=a.next();!c.done;c=a.next())if(c=c.value,void 0!=c&&(isRoad(c.tileid)||isFence(c.tileid))&&c.posx==b.posx+tileSize&&c.posy==b.posy&&(isFence(c.tileid)&&isFence(b.tileid)||isRoad(c.tileid)&&isRoad(b.tileid)))return c;return null}
function getLeftx(b){for(var a=$jscomp.makeIterator(cellsArray),c=a.next();!c.done;c=a.next())if(c=c.value,void 0!=c&&(isRoad(c.tileid)||isFence(c.tileid))&&c.posx==b.posx-tileSize&&c.posy==b.posy&&(isFence(c.tileid)&&isFence(b.tileid)||isRoad(c.tileid)&&isRoad(b.tileid)))return c;return null}
function getUpx(b){for(var a=$jscomp.makeIterator(cellsArray),c=a.next();!c.done;c=a.next())if(c=c.value,void 0!=c&&(isRoad(c.tileid)||isFence(c.tileid))&&c.posx==b.posx&&c.posy==b.posy-tileSize&&(isFence(c.tileid)&&isFence(b.tileid)||isRoad(c.tileid)&&isRoad(b.tileid)))return c;return null}
function getDownx(b){for(var a=$jscomp.makeIterator(cellsArray),c=a.next();!c.done;c=a.next())if(c=c.value,void 0!=c&&(isRoad(c.tileid)||isFence(c.tileid))&&c.posx==b.posx&&c.posy==b.posy+tileSize&&(isFence(c.tileid)&&isFence(b.tileid)||isRoad(c.tileid)&&isRoad(b.tileid)))return c;return null}function isRoad(b){return 0<=b&&15>=b?!0:!1}function isFence(b){return 68<=b&&83>=b?!0:!1}
function redrawMapCells(){context2.clearRect(0,0,5100,5100);var b=Object.entries(cellsArray).sort(function(g,k){return g[1].tileid-k[1].tileid});b=$jscomp.makeIterator(b);for(var a=b.next();!a.done;a=b.next())if(a=a.value,a=a[1],void 0!=a)if(isFence(a.tileid)||isRoad(a.tileid)){var c=(a.posy+tileSize)/tileSize,d=a.posx/tileSize;noWalkableEditor.includes(parseInt(a.tileid))&&(matrix[c][d]=1);isRoad(a.tileid)&&(matrix[c][d]=2);if(0!=a.objtile){c=getRightx(a);d=getLeftx(a);var e=getUpx(a),f=getDownx(a);
if(null==c&&null!=d&&null==e&&null==f){if(isRoad(a.tileid))a.tileid=2;else if(isFence(a.tileid))a.tileid=70;else continue;a.image=tilePreloadMap[a.tileid].image}else if(null!=c&&null==d&&null==e&&null==f){if(isRoad(a.tileid))a.tileid=3;else if(isFence(a.tileid))a.tileid=71;else continue;a.image=tilePreloadMap[a.tileid].image}else if(null==c&&null==d&&null==e&&null!=f){if(isRoad(a.tileid))a.tileid=11;else if(isFence(a.tileid))a.tileid=79;else continue;a.image=tilePreloadMap[a.tileid].image}else if(null==
c&&null==d&&null!=e&&null==f){if(isRoad(a.tileid))a.tileid=5;else if(isFence(a.tileid))a.tileid=73;else continue;a.image=tilePreloadMap[a.tileid].image}else if(null!=c&&null!=d&&null!=e&&null!=f){if(isRoad(a.tileid))a.tileid=6;else if(isFence(a.tileid))a.tileid=74;else continue;a.image=tilePreloadMap[a.tileid].image}else if(null!=c&&null!=d&&null==e&&null==f){if(isRoad(a.tileid))a.tileid=1;else if(isFence(a.tileid))a.tileid=69;else continue;a.image=tilePreloadMap[a.tileid].image}else if(null==c&&
null!=d&&null!=e&&null==f){if(isRoad(a.tileid))a.tileid=12;else if(isFence(a.tileid))a.tileid=80;else continue;a.image=tilePreloadMap[a.tileid].image}else if(null==c&&null!=d&&null==e&&null!=f){if(isRoad(a.tileid))a.tileid=13;else if(isFence(a.tileid))a.tileid=81;else continue;a.image=tilePreloadMap[a.tileid].image}else if(null!=c&&null==d&&null==e&&null!=f){if(isRoad(a.tileid))a.tileid=9;else if(isFence(a.tileid))a.tileid=77;else continue;a.image=tilePreloadMap[a.tileid].image}else if(null!=c&&null==
d&&null!=e&&null==f){if(isRoad(a.tileid))a.tileid=14;else if(isFence(a.tileid))a.tileid=82;else continue;a.image=tilePreloadMap[a.tileid].image}else if(null!=c&&null==d&&null!=e&&null!=f){if(isRoad(a.tileid))a.tileid=15;else if(isFence(a.tileid))a.tileid=83;else continue;a.image=tilePreloadMap[a.tileid].image}else if(null==c&&null!=d&&null!=e&&null!=f){if(isRoad(a.tileid))a.tileid=8;else if(isFence(a.tileid))a.tileid=76;else continue;a.image=tilePreloadMap[a.tileid].image}else if(null!=c&&null!=d&&
null==e&&null!=f){if(isRoad(a.tileid))a.tileid=4;else if(isFence(a.tileid))a.tileid=72;else continue;a.image=tilePreloadMap[a.tileid].image}else if(null==c&&null==d&&null!=e&&null!=f){if(isRoad(a.tileid))a.tileid=10;else if(isFence(a.tileid))a.tileid=78;else continue;a.image=tilePreloadMap[a.tileid].image}else if(null!=c&&null!=d&&null!=e&&null==f){if(isRoad(a.tileid))a.tileid=7;else if(isFence(a.tileid))a.tileid=75;else continue;a.image=tilePreloadMap[a.tileid].image}if(null==c&&null==d&&null==e&&
null==f){if(isRoad(a.tileid))a.tileid=0;else if(isFence(a.tileid))a.tileid=68;else continue;a.image=tilePreloadMap[a.tileid].image}}a.draw()}else 1<=performanceMode&&a.draw();easystar.setGrid(matrix)}function onlyLettersAndSpaces(b){return/^[A-Za-z0-9\s@!@#\$%\^&\/*:\?\)\(+=._-]*$/.test(b)}
function chatConnect(){socketChat=new WebSocket(apichat);clearInterval(chatPing);socketChat.onopen=function(b){document.getElementsByClassName("warniconchat")[0].style.display="none";document.getElementsByClassName("chatbtns")[0].style.display="flex";connectedChat?document.getElementsByClassName("chatcontainer")[0].classList.contains("chathidden")&&maximizeChat():(connectedChat=!0,document.getElementsByClassName("chatcontainer")[0].addEventListener("click",function(){zindexWindow+=1;this.style.zIndex=
zindexWindow}),document.getElementsByClassName("btnminimchat")[0].addEventListener("click",function(){clickSound.play();this.classList.contains("minmchatactive")?maximizeChat():minimizeChat()}),document.getElementsByClassName("btnmaxchat")[0].addEventListener("click",function(){clickSound.play();switch(startHeightChat){case 30:startHeightChat=50;break;case 50:startHeightChat=70;break;case 70:startHeightChat=85;break;case 85:startHeightChat=30}document.getElementsByClassName("chatcontainer")[0].style.height=
startHeightChat+"%";Draggable.get(".chatcontainer").applyBounds(window)}),show(document.getElementsByClassName("chatcontainer")[0]),Draggable.create(".chatcontainer",{onPress:function(){if(this.target.classList.contains("chathidden"))return this.endDrag(),!1;Bounds(this,0,125)},onDragEnd:function(a){zindexWindow+=1;this.target.style.zIndex=zindexWindow},type:"x,y",inertia:!1,zIndexBoost:!1,edgeResistance:1,trigger:".chatbox-top"}),document.getElementById("textchatinput").addEventListener("input",
function(a){a.target.value.startsWith("!")&&0>=buclChat?(showtimer&&(show(document.getElementsByClassName("btnsendchatcom")[0]),hide(document.getElementsByClassName("btnsendchatmsg")[0])),showtimer=!1):(showtimer||(hide(document.getElementsByClassName("btnsendchatcom")[0]),show(document.getElementsByClassName("btnsendchatmsg")[0])),showtimer=!0)}),document.getElementById("textchatinput").addEventListener("keypress",function(a){var c=a.key.toLowerCase();if("enter"==c)return document.getElementById("textchatinput").value.startsWith("!")&&
0>=buclChat?processCommand():sendChatMessage(),!1;onlyLettersAndSpaces(c)||a.preventDefault()}),document.getElementsByClassName("btnsendchatmsg")[0].addEventListener("click",function(a){a.stopImmediatePropagation();a.stopPropagation();a.preventDefault();document.getElementById("textchatinput").value.startsWith("!")&&0>=buclChat?processCommand():sendChatMessage()}),document.getElementsByClassName("btnsendchatcom")[0].addEventListener("click",function(a){a.stopImmediatePropagation();a.stopPropagation();
a.preventDefault();document.getElementById("textchatinput").value.startsWith("!")?processCommand():sendChatMessage()}));socketChat.send(JSON.stringify({action:"login",wallet:userInfo.account,key:userInfo.secretkey}));chatPing=setInterval(function(){socketChat.send(JSON.stringify({action:"ping"}))},15E3)};socketChat.onmessage=function(b){b=JSON.parse(b.data);if(void 0==b.action)b.forEach(function(g){addMsgChat(g.data.wallet,userInfo.account,g.data.msg,g.date)});else switch(b.action){case "listwithdraw":exchTrans=
b.transacts;renderExchContent(!1);break;case "nochat":reconnectChat=!1;makeNotif(1,"Chat temporally closed");document.getElementsByClassName("chatcontainer")[0].remove();break;case "actmsg":addMsgChat(b.data.wallet,userInfo.account,b.data.msg,b.date);break;case "inittimer":0<b.timer&&initTimerChat(b.timer);break;case "chest":if(void 0!=document.querySelectorAll('[data-chestopen="chest"]')[0]){var a=b.wallet;if(JSON.parse(b.success)){var c=b.infosucc.date,d=b.infosucc.data.wallet,e=b.infosucc.data.msg,
f=a.replace(a.substring(6,36),"****");addMsgChat(d,userInfo.account,'<a href="https://bscscan.com/address/'+a+'" target="_blank">'+f+"</a>"+e,c)}a!=userInfo.account&&(document.getElementsByClassName("txtprobi")[0].innerText=b.prob+"%",document.getElementsByClassName("txtchvaluech")[0].innerText=b.gold,document.getElementsByClassName("txtpricevaluech")[0].innerText=b.cost,a=parseInt(b.datewinner),c="None",b=b.lastwinner,0==a?a="None":(c='<a href="'+blockeExplorerUrl+"/address/"+b+'" target="_blank">'+
b.replace(b.substring(6,36),"****")+"</a>",a=(new Date(a)).toLocaleString()),document.getElementsByClassName("txtlastwinnerchest")[0].innerHTML=c,document.getElementsByClassName("txtdatewinner")[0].innerText=a)}break;case "sumgold":referredP=b.listref;userInfo.quests=b.quests;loadQuestPanel();renderRefContent(!1);updateUserStats({gold:b.quant},!1);break;case "duplicate":reconnectChat=!1,loadingScreen(!0),document.getElementsByClassName("alertmsgmid")[0].innerHTML="Game disconnected, another session with the same account has been detected",
show(document.getElementsByClassName("draghead4")[0]),document.getElementsByClassName("screen-lock-text")[0].innerText="",document.getElementsByClassName("draghead4")[0].style.zIndex=1100,document.getElementsByClassName("chatcontainer")[0].remove(),document.getElementsByClassName("bottombar")[0].remove(),clearInterval(chatPing),socketChat.close()}};socketChat.onclose=function(b){reconnectChat&&(document.getElementsByClassName("chatcontainer")[0].classList.contains("chathidden")||document.getElementsByClassName("chatcontainer")[0].classList.add("chathidden"),
document.getElementsByClassName("warniconchat")[0].style.display="block",hide(document.getElementsByClassName("chatbtns")[0]),setTimeout(function(){chatConnect()},2E3))}}function validateYouTubeUrl(b){b=b.replace("http://","https://");return 43<b.length||!b.startsWith("https://")?!1:(b=b.match(/^(?:https?:\/\/)?(?:www\.)?(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|watch\?.+&v=))((\w|-){11})(?:\S+)?$/))?b[1]:!1}
function createDivs(b,a,c){var d=Math.floor(99999*Math.random());zindexWindow+=1;document.body.insertAdjacentHTML("beforeend",'<div style="z-index:'+zindexWindow+'" id="tr'+d+'" data-pnlid="'+d+'" class="'+a+' game-borders"> <div class="container"> <div class="row"> <div id="ctn'+d+'" class="containercdiv">'+b+'</div><div class="buttonlists">'+c+'<div onclick="closePanelDiv(this,'+d+')" data-panelid="'+d+'" class="smallbtn closehelp"><div class="innersmall">Close</div></div></div></div></div></div></div>');
Draggable.create("#tr"+d,{onPress:function(){Bounds(this,0,135);zindexWindow+=1;this.target.style.zIndex=zindexWindow},onDragEnd:function(e){zindexWindow+=1;this.target.style.zIndex=zindexWindow},type:"x,y",inertia:!1,edgeResistance:1,zIndexBoost:!1,trigger:"#ctn"+d,bounds:window})}function closePanelDiv(b,a){clickSound.play();void 0!=Draggable.get("#tr"+a)&&Draggable.get("#tr"+a).kill();document.querySelectorAll('[data-pnlid="'+b.dataset.panelid+'"]')[0].remove()}
function processCommand(){var b=document.getElementById("textchatinput").value;if(""==b)return!1;if(!onlyLettersAndSpaces(b))return makeNotif(2,"Invalid characters"),!1;if(100<b.length)return makeNotif(2,"The maximum length of the message cannot exceed 100 characters"),!1;var a=b.substring(1),c=a.split(" ")[1],d=a.split(" ")[2];a=a.split(" ")[0];switch(a){case "help":validComm("","","",!1);createDivs('Available commands:</div><div class="containedmiddiv"><div class="texthouse">Embed YouTube video:</br></br><span class="text-primary">!yt</span> <span class="text-primary">{link}</span> <span class="text-success">{text optional}</span></br><span class="text-warning">!yt https://youtube.com/watch?v=xxxxxxxxxx MediTown</span><div class="separatorline"></div>Repair Transaction:</br></br><span class="text-primary">!hash</span> <span class="text-primary">{transaction hash}</span></br><span class="text-warning">!hash 0xxxxxxxxxxxxxxxx</span></div>',
"createddiv","");break;case "hash":if(66!=c.length)return makeNotif(1,"Invalid hash"),!1;loadingScreen(!0);validComm("","","",!1);checkHash(c,null);break;case "yt":case "youtube":if(void 0==c)return makeNotif(2,"Invalid YouTube link"),!1;validateYouTubeUrl(c)?(""!=d&&void 0!=d&&(d=b.substring(a.length+c.length+3)),validComm(c,d,a,!0)):makeNotif(2,"Invalid YouTube link")}}
function maximizeChat(){show(document.getElementsByClassName("btnmaxchat")[0]);document.getElementsByClassName("chatcontainer")[0].classList.remove("chathidden");document.getElementsByClassName("btnminimchat")[0].classList.remove("minmchatactive");document.getElementsByClassName("chatcontainer")[0].classList.remove("game-bordersr");document.getElementsByClassName("chatcontainer")[0].classList.add("game-borders");TweenLite.set(".chatcontainer",{x:0,y:0});Bounds(Draggable.get(".chatcontainer"),0,125)}
var mobile_nav_toggle=document.createElement("button");mobile_nav_toggle.id="mobile-nav-toggle";mobile_nav_toggle.classList="nodisplay";mobile_nav_toggle.type="button";mobile_nav_toggle.innerHTML='<i class="bi bi-list"></i>';document.body.prepend(mobile_nav_toggle);document.getElementsByClassName("optionsmobile")[0].addEventListener("click",function(b){btnPressedMobile();document.getElementsByClassName("optionbtn")[0].click()});
document.getElementById("mobile-nav-toggle").addEventListener("click",function(b){btnPressedMobile()});
function btnPressedMobile(){document.body.classList.toggle("mobile-nav-active");var b=document.querySelector("#mobile-nav-toggle i");b.classList.toggle("bi-x");b.classList.toggle("bi-list");b=document.querySelector("#mobile-body-overly");""==b.style.display&&(b.style.display="none");"none"==b.style.display&&(document.getElementsByClassName("foodquantmobile")[0].innerText=document.getElementsByClassName("foodquant")[0].innerText,document.getElementsByClassName("woodquantmobile")[0].innerText=document.getElementsByClassName("woodquant")[0].innerText,
document.getElementsByClassName("coalquantmobile")[0].innerText=document.getElementsByClassName("coalquant")[0].innerText,document.getElementsByClassName("goldquantmobile")[0].innerText=document.getElementsByClassName("goldquant")[0].innerText,document.getElementsByClassName("timemobile")[0].innerText=document.getElementsByClassName("realquant")[0].innerText,document.getElementsByClassName("walletmobile")[0].innerText=document.getElementsByClassName("walletacc")[0].innerText);b.style.display="block"===
b.style.display?"none":"block"}
function minimizeChat(){startHeightChat=30;document.getElementsByClassName("chatcontainer")[0].style.height=startHeightChat+"%";document.getElementsByClassName("chatcontainer")[0].classList.add("chathidden");document.getElementsByClassName("btnminimchat")[0].classList.add("minmchatactive");document.getElementsByClassName("chatcontainer")[0].classList.add("game-bordersr");document.getElementsByClassName("chatcontainer")[0].classList.remove("game-borders");hide(document.getElementsByClassName("btnmaxchat")[0]);hide(document.getElementsByClassName("btnclschat")[0])}
function validComm(b,a,c,d){d&&(void 0==a&&(a=""),socketChat.send(JSON.stringify({action:"sendmsg",msg:b,type:"public",extra:a,command:c})),initTimerChat(timeWaitChat));document.getElementById("textchatinput").value="";hide(document.getElementsByClassName("btnsendchatcom")[0]);show(document.getElementsByClassName("btnsendchatmsg")[0])}
function sendChatMessage(){if(document.getElementsByClassName("btnsendchatmsg")[0].classList.contains("disabled"))return!1;var b=document.getElementById("textchatinput").value;if(""==b)return!1;if(!onlyLettersAndSpaces(b))return makeNotif(2,"Invalid characters"),!1;if(100<b.length)return makeNotif(2,"The maximum length of the message cannot exceed 100 characters"),!1;document.getElementById("textchatinput").value="";b={action:"sendmsg",msg:b,type:"public",extra:""};initTimerChat(timeWaitChat);socketChat.send(JSON.stringify(b))}
function initTimerChat(b){document.getElementsByClassName("btnsendchatmsg")[0].classList.contains("disabled")||document.getElementsByClassName("btnsendchatmsg")[0].classList.add("disabled");buclChat=b;document.getElementsByClassName("btnsendchatmsg")[0].innerText=buclChat;clearInterval(intervalChat);intervalChat=setInterval(function(){if(0>=buclChat)return clearInterval(intervalChat),document.getElementsByClassName("btnsendchatmsg")[0].classList.contains("disabled")&&document.getElementsByClassName("btnsendchatmsg")[0].classList.remove("disabled"),
document.getElementsByClassName("btnsendchatmsg")[0].innerText="Send",!1;--buclChat;document.getElementsByClassName("btnsendchatmsg")[0].innerText=buclChat},1E3)}function getIdYT(b){return(b=b.match(/^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]*).*/))&&11===b[2].length?b[2]:null}
function windowYT(b){var a=Math.floor(99999*Math.random());linkyt=getIdYT(b.dataset.link);zindexWindow+=1;document.body.insertAdjacentHTML("beforeend",'<div id="tr'+a+'" style="z-index:'+zindexWindow+'" data-pnlid="'+a+'" class="createddiv game-borders"> <div class="container"> <div class="row"> <div id="ctn'+a+'" class="containercdiv">YT Video:</div><div class="containedmiddiv"><div class="texthouse"><iframe width="100%" height="315" src="https://www.youtube-nocookie.com/embed/'+linkyt+'" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><div class="buttonlists"><div onclick="closePanelDiv(this,'+
a+')" data-panelid="'+a+'" class="smallbtn closehelp"><div class="innersmall">Close</div></div></div></div></div></div></div>');Draggable.create("#tr"+a,{onPress:function(){Bounds(this,0,135)},onDragEnd:function(c){zindexWindow+=1;this.target.style.zIndex=zindexWindow},type:"x,y",inertia:!1,zIndexBoost:!1,edgeResistance:1,trigger:"#ctn"+a,bounds:window})}
function addMsgChat(b,a,c,d){b==a?b='<div data-chatid="'+d+'" class="message-box-holder"><div class="message-box">'+c+"</div></div>":(walletAdmin==b&&(b="Admin"),42==b.length&&(b=b.replace(b.substring(6,36),"****")),b='<div data-chatid="'+d+'" class="message-box-holder"><div class="message-sender">'+b+'</div> <div class="message-box message-partner">'+c+"</div></div>");totalMessages.push(d);30<totalMessages.length&&(d=totalMessages.shift(),void 0!=document.querySelectorAll('[data-chatid="'+d+'"]')[0]&&
document.querySelectorAll('[data-chatid="'+d+'"]')[0].remove());document.getElementsByClassName("chat-messages")[0].insertAdjacentHTML("beforeend",b);d=document.getElementsByClassName("chat-messages")[0];d.scrollTop=d.scrollHeight};